
const main = async () => {
	try{
		return
	}catch(err){
		console.log(err)
		throw new Error("[ERROR] Fatal ERROR")
	}
}
main()

export default {
	
}